# Homebrew formula for swarmexec 1.22.0 — generated by ci/package-manifests.sh.
class Swarmexec < Formula
  desc "Exec, logs and port-forward into any container of a Docker Swarm, without SSH"
  homepage "https://swarm-exec.cloud-surfers.net"
  version "1.22.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.0/swarmexec-darwin-arm64"
      sha256 "429f07009f5b14e094c112e175b38b3b53ebbadca63e19320f2483d56ffa6d5f"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.0/swarmexec-darwin-amd64"
      sha256 "a2a2f20d9bc1b7610b2006309a0fdd6a57e2942ff8ce63f8ab359b0e33aec1a8"
    end
  end

  on_linux do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.0/swarmexec-linux-arm64"
      sha256 "e4e58165423be96aa565e825acc6306f5efb97e7ddacf3e067e57cf72a8b94a2"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.0/swarmexec-linux-amd64"
      sha256 "d6f9f1021fe7f4577a6afc929b0b87c8511c7e5da06fd51afb8934298d925790"
    end
  end

  def install
    # The release ships bare binaries, not archives: install whichever one was
    # downloaded for this platform under its real name.
    bin.install Dir["swarmexec-*"].first => "swarmexec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/swarmexec --version")
  end
end
