# Homebrew formula for swarmexec 1.22.2 — generated by ci/package-manifests.sh.
class Swarmexec < Formula
  desc "Exec, logs and port-forward into any container of a Docker Swarm, without SSH"
  homepage "https://swarm-exec.cloud-surfers.net"
  version "1.22.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.2/swarmexec-darwin-arm64"
      sha256 "dea766f2ec7da859a64d8c11a1b22b1ef27cb0e46f1987f17850b0ce038b131a"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.2/swarmexec-darwin-amd64"
      sha256 "9fb64b32933d41dfebe446b9977310f95beae18bd7ec29105e72cdba5b45fe93"
    end
  end

  on_linux do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.2/swarmexec-linux-arm64"
      sha256 "8ed412af9d14f4f18a194bb265834c9e5543d88a7f5c71672ca971a0d39ebddb"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.22.2/swarmexec-linux-amd64"
      sha256 "c6acb19fbbd666c233ee57f6a49385edd73558fae5a40763a67d0df1532673af"
    end
  end

  def install
    # The release ships bare binaries, not archives: install whichever one was
    # downloaded for this platform under its real name.
    bin.install Dir["swarmexec-*"].first => "swarmexec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/swarmexec --version")
  end
end
