# Homebrew formula for swarmexec 1.20.0 — generated by ci/package-manifests.sh.
class Swarmexec < Formula
  desc "Exec, logs and port-forward into any container of a Docker Swarm, without SSH"
  homepage "https://swarm-exec.cloud-surfers.net"
  version "1.20.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.20.0/swarmexec-darwin-arm64"
      sha256 "2014fc40b345ae9caeaf6a2c00e93494979c25767e24ac5d5a440f53a0fa4439"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.20.0/swarmexec-darwin-amd64"
      sha256 "d94e0b47ce1afb74d915f1633b0e81a869ba2ae46b2639958698ab0fd3bcdf96"
    end
  end

  on_linux do
    on_arm do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.20.0/swarmexec-linux-arm64"
      sha256 "9f78be77e8ba41e0a1cd560a54ce6b233ace44813768c5d54e8a815dea42b497"
    end
    on_intel do
      url "https://gitlab.logle.io/api/v4/projects/242/packages/generic/swarmexec/v1.20.0/swarmexec-linux-amd64"
      sha256 "9730166e4c080a2dcc60ecad009b92b34ceb87209a20ddb4a1f7f4631c7e9a59"
    end
  end

  def install
    # The release ships bare binaries, not archives: install whichever one was
    # downloaded for this platform under its real name.
    bin.install Dir["swarmexec-*"].first => "swarmexec"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/swarmexec --version")
  end
end
